version: '3.8'

services:
  postgres:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-froullete}
      POSTGRES_USER: ${POSTGRES_USER:-froullete}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-froullete}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  nxginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: "./nginx"
    ports:
      - "3050:80"

  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: './api'
    depends_on:
      - postgres
    volumes:
      - /api/node_modules
      - ./api:/api
    ports:
      - '3001:3000'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-froullete}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-froullete}
      POSTGRES_DB: ${POSTGRES_DB:-froullete}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}

  client:
    build:
      dockerfile: Dockerfile
      context: "./client"
    depends_on:
      - api # todo: might not be necessary
    volumes:
      - /client/node_modules
      - ./client:/app
    ports:
      - "3000:3000"

volumes:
  pg_data:
